project:
  type: website
  output-dir: build

website:
  title: "OpenSustain AI"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/brt-rj/OpenSustain-AI-Engine
        aria-label: GitHub
  
  site-url: /brt-serve/projects/OpenSustain-AI-Engine

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
