project:
  type: website
  output-dir: build

website:
  title: "MS-RAP"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/brt-rj/RAP-Scout
        aria-label: GitHub
  
  site-url: /brt-serve/projects/RAP-Scout

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
